name: Gang
version: '${project.version}-${devbuild.version}'
main: net.danh.gang.Gang
depend: [ Vault, PlaceholderAPI ]
authors: [ VoChiDanh ]
commands:
  gang:
    description: Main Gang command.
    aliases: [ g ]
