name: Gang
version: '${project.version}'
main: net.danh.gang.Gang
depend: [ Vault, PlaceholderAPI ]
softdepend:
  - Fee
  - Jobs
authors: [ VoChiDanh ]
commands:
  gang:
    description: Main Gang command.
    aliases: [ g ]
